export const appRoutes = {
  login: "/login",
  appHome: "/app",
  tenants: "/app/tenants",
  users: "/app/users",
  teachers: "/app/teachers",
  classes: "/app/classes",
  subjectGroups: "/app/subject-groups",
  courses: "/app/courses",
  courseMonitoring: "/app/course-monitoring",
  learn: "/app/learn",
  exams: "/app/exams",
  students: "/app/students",
  gallery: "/app/gallery",
  phaseOneReview: "/app/phase-1-review",
  settings: "/app/settings",
} as const;
